name: handbrake-gui # Change to handbrake for official release
adopt-info: handbrake
confinement: strict
base: core22
compression: lzo
architectures:
  - build-on: amd64
  - build-on: arm64

apps:
  handbrake:
    command: usr/bin/ghb
    common-id: fr.handbrake.ghb.desktop
    desktop: usr/share/applications/fr.handbrake.ghb.desktop
    extensions: [gnome]
    plugs:
      - home
      - removable-media
      - screen-inhibit-control
      - shutdown
      - upower-observe
    environment:
      LIBVA_DRIVERS_PATH: $SNAP/intel-plugin/lib/$CRAFT_ARCH_TRIPLET/dri
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/intel-plugin/lib/$CRAFT_ARCH_TRIPLET:$SNAP/usr/lib/${CRAFT_ARCH_TRIPLET}/blas:$SNAP/usr/lib/${CRAFT_ARCH_TRIPLET}/lapack
  cli:
    command: usr/bin/HandBrakeCLI
    common-id: fr.handbrake.HandBrakeCLI
    extensions: [gnome]
    plugs:
      - home
      - removable-media
    environment:
      LIBVA_DRIVERS_PATH: $SNAP/intel-plugin/lib/$CRAFT_ARCH_TRIPLET/dri
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/intel-plugin/lib/$CRAFT_ARCH_TRIPLET

# Allows plugins for hardware acceleration to be mounted
plugs:
  intel-0-2204: # plugin_name-api_version-ubuntu_base
    interface: content
    content: intel-0-2204
    target: $SNAP/intel-plugin/lib

parts:
  handbrake:
    source-type: git
    source: https://github.com/robxnano/handbrake.git
    source-branch: snap-static
    parse-info: [usr/share/metainfo/fr.handbrake.ghb.metainfo.xml]
    plugin: make
    override-pull: |
      craftctl default
      GIT_TAG="`git describe --tags | cut -f1 -d-`"
      GIT_REV="`git describe --tags | cut -f3 -d- | sed 's/g//'`"
      if [ -n "$GIT_REV" ]; then
        craftctl set version="$GIT_TAG-git-$GIT_REV"
        craftctl set grade="devel"
      else
        craftctl set version="$GIT_TAG"
        craftctl set grade="stable"
      fi
    # cargo-c is not in the Ubuntu 22.04 repositories so use the rustup toolchain
    override-build: |
      curl https://sh.rustup.rs -sSf | sh -s -- -y --no-modify-path --profile minimal
      export PATH=$HOME/.cargo/bin:$PATH
      cargo install cargo-c
      cd ..
      rm -rf build
      mkdir -p build
      cd build
      if [ "$CRAFT_TARGET_ARCH" = "amd64" ]; then
        FLAG_QSV=--enable-qsv
      else
        FLAG_QSV=--disable-qsv
      fi
      ${CRAFT_PART_SRC}/configure --prefix=/usr "$FLAG_QSV" --disable-nvenc --disable-nvdec --disable-vce --snap
      craftctl default
    build-packages:
      - autoconf
      - automake
      - autopoint
      - cmake
      - curl
      - libass-dev
      - libbz2-dev
      - libgstreamer-plugins-bad1.0-dev
      - libicu-dev
      - libjansson-dev
      - libmp3lame-dev
      - libnuma-dev
      - libopus-dev
      - libspeex-dev
      - libssl-dev # needed to build cargo-c
      - libtheora-dev
      - libtool
      - libtool-bin
      - libturbojpeg0-dev
      - libvorbis-dev
      - libvpx-dev
      - libx264-dev
      - nasm
      - pkg-config # needed to build cargo-c
      - zlib1g-dev # needed to build cargo-c
    prime:
      - -usr/etc
      - -usr/include
      - -usr/lib/$CRAFT_ARCH_TRIPLET/cmake
      - -usr/lib/$CRAFT_ARCH_TRIPLET/lib*.a
      - -usr/lib/$CRAFT_ARCH_TRIPLET/lib*.la
      - -usr/lib/$CRAFT_ARCH_TRIPLET/lib*.so
      - -usr/lib/$CRAFT_ARCH_TRIPLET/pkgconfig
      - -usr/lib/pkgconfig
      - -usr/share/doc
      - -usr/share/ffmpeg
      - -usr/share/vpl

  libraries: # Only use libraries required by ghb or libgstlibav.so
    plugin: nil
    stage-packages:
      - gstreamer1.0-libav
      - libass9
      - libblas3
      - libjansson4
      - libnuma1
      - libturbojpeg
      - libx264-163
    prime:
      - -usr/bin/fc-*
      - -usr/bin/update-mime-database
      - -usr/share/alsa
      - -usr/share/apport
      - -usr/share/bug
      - -usr/share/doc
      - -usr/share/doc-base
      - -usr/share/fonts
      - -usr/share/gettext
      - -usr/share/gst-plugins-base
      - -usr/share/iso-codes
      - -usr/share/libmysofa
      - -usr/share/libthai
      - -usr/share/lintian
      - -usr/share/man
      - -usr/share/mfx
      - -usr/share/mime
      - -usr/share/pkgconfig
      - -usr/share/X11
      - -usr/share/xml
      - -usr/lib/${CRAFT_ARCH_TRIPLET}/gdk-pixbuf-2.0
      - -usr/lib/${CRAFT_ARCH_TRIPLET}/gstreamer1.0
      - -usr/lib/${CRAFT_ARCH_TRIPLET}/gstreamer-1.0/libgstcoreelements.so
      - -usr/lib/${CRAFT_ARCH_TRIPLET}/gstreamer-1.0/libgstcoretracers.so
      - -usr/lib/${CRAFT_ARCH_TRIPLET}/libcairo-gobject.so*
      - -usr/lib/${CRAFT_ARCH_TRIPLET}/libcairo.so*
      - -usr/lib/${CRAFT_ARCH_TRIPLET}/libdw.so*
      - -usr/lib/${CRAFT_ARCH_TRIPLET}/libdw-0.*.so
      - -usr/lib/${CRAFT_ARCH_TRIPLET}/libflite_cmu_grapheme_lang.so*
      - -usr/lib/${CRAFT_ARCH_TRIPLET}/libflite_cmu_grapheme_lex.so*
      - -usr/lib/${CRAFT_ARCH_TRIPLET}/libflite_cmu_indic_lang.so*
      - -usr/lib/${CRAFT_ARCH_TRIPLET}/libflite_cmu_indic_lex.so*
      - -usr/lib/${CRAFT_ARCH_TRIPLET}/libflite_cmu_time_awb.so*
      - -usr/lib/${CRAFT_ARCH_TRIPLET}/libgdk_pixbuf-2.0.so*
      - -usr/lib/${CRAFT_ARCH_TRIPLET}/libharfbuzz.so*
      - -usr/lib/${CRAFT_ARCH_TRIPLET}/libmfx-tracer.so*
      - -usr/lib/${CRAFT_ARCH_TRIPLET}/libmfxhw64.so*
      - -usr/lib/${CRAFT_ARCH_TRIPLET}/libpango-1.0.so*
      - -usr/lib/${CRAFT_ARCH_TRIPLET}/libpangocairo-1.0.so*
      - -usr/lib/${CRAFT_ARCH_TRIPLET}/libpangocairo-1.0.so*
      - -usr/lib/${CRAFT_ARCH_TRIPLET}/libpangoft2-1.0.so*
      - -usr/lib/${CRAFT_ARCH_TRIPLET}/libpixman-1.so*
      - -usr/lib/${CRAFT_ARCH_TRIPLET}/libsphinxad.so*
      - -usr/lib/${CRAFT_ARCH_TRIPLET}/libva-drm.so*
      - -usr/lib/${CRAFT_ARCH_TRIPLET}/libva-x11.so*
      - -usr/lib/${CRAFT_ARCH_TRIPLET}/libva.so*
      - -usr/lib/${CRAFT_ARCH_TRIPLET}/libzvbi-chains.so*
      - -usr/lib/${CRAFT_ARCH_TRIPLET}/mfx
      - -usr/lib/${CRAFT_ARCH_TRIPLET}/pulseaudio
      - -usr/lib/${CRAFT_ARCH_TRIPLET}/vdpau

  # Find files provided by the base and platform snap and ensure they aren't
  # duplicated in this snap
  cleanup:
    after: [libraries]
    plugin: nil
    build-snaps: [core22, gtk-common-themes, gnome-42-2204]
    override-prime: |
      set -eux
      for snap in "core22" "gtk-common-themes" "gnome-42-2204"; do
        cd "/snap/$snap/current" && find . -type f,l -name *.so.* -exec rm -f "$CRAFT_PRIME/{}" \;
      done

